### ISSUE TITLE
Catalogue seems to save the resulting .exr in the wrong directory

### ISSUE THREAD

**Issue by boberfly** [hypothetical-inc/gaffer#14]
**Version**: Gaffer 0.54.2.0-windows
**Third-party modules:** GafferCycles

### Description ###

I don't think this is a GafferCycles-specific bug, but when I render from the Catalogue and stop the render, it seems like the resulting .exr is trying to save in the wrong place., which might be a forward/backslash issue.

### Steps to reproduce ###

1. Render an interactive render with a catalogue node.
2. Stop the render.
3. Catalogue errors trying to load the resulting .exr due to the wrong path.

### Debug log ###

<details>
<summary>Click to Expand</summary><p>

```
File gets saved here:
C:\Users\Alex\gaffer\projects\defaultcatalogues\ef7fbdcb4c876f9f60e03a36e2e074c2.exr

But in Gaffer the Catalogue node has a red warning sign and is trying to load it from:
C:\Users\Alex\gaffer\projects\defaultcataloguestest\ef7fbdcb4c876f9f60e03a36e2e074c2.exr

My gfr file is saved here:
C:\Users\Alex\gaffer\projects\default\scripts\test.gfr

On Linux it should be:
/home/alex/gaffer/projects/default/catalogues/test/ef7fbdcb4c876f9f60e03a36e2e074c2.exr

So 'defaultcataloguestest' should have slashes in-between most likely.
```
</p>
</details>

**Comment by ericmehl** [comment]
Thanks for flagging that Alex - I see what's going on but I need to think through the best solution. 

There are some tricky things that come up with string substitution and the slashes in general that I'd like to try and find a better solution than I have now. There are places in Gaffer where the order of substitute + get filename vs. get filename + substitute make for a hard time to know when to convert path separators.

More to come soon!

**Comment by ericmehl** [comment]
Looks like I sorted it - not quite what I laid out in the last post but roughly similar. This is a really useful fix so I'll put up a patch release when it clears my CI.

Thanks again for pointing it out Alex!

**Comment by ericmehl** [comment]
Fix is up! Give https://github.com/hypothetical-inc/gaffer/releases/tag/0.55.2.1 a try and see how that works for you.

**Comment by aditiapratama** [comment]
no windows build for this release @ericmehl ?

**Comment by ericmehl** [comment]
Huh, it must not have gotten attached correctly. Check it again @aditiapratama and the binary release should be there. Same link as before: https://github.com/hypothetical-inc/gaffer/releases/tag/0.55.2.1

**Comment by boberfly** [comment]
Nice one @ericmehl I'll give it a test when I get the time. Cheers!

**Comment by boberfly** [comment]
Hey @ericmehl 

This works great, sorry I haven't had the chance to close this bug. New 0.16.0 of GafferCycles build coming soon once I get around the weird cmake changes the blender guys made to the standalone branch... :)
