### ISSUE TITLE
Can not load usd/usda file

### ISSUE THREAD

**Issue by xtvjxk123456** [hypothetical-inc/gaffer#20]
**Version**: 0.57.3.0
**Third-party tools:** Arnold
**Third-party modules:** 

### Description ###

Can not load usd/usda file. console show IO exception

### Steps to reproduce ###

use SceneReader to read usd/usda file

### Debug log ###

![Snipaste_2020-05-28_14-26-56](https://user-images.githubusercontent.com/8720281/83106604-56ac9400-a0ef-11ea-9b4d-c973c8fe440f.jpg)

**Comment by ericmehl** [comment]
I see the problem, looks like USD on Windows doesn't install Python modules to the same place as Linux so they aren't getting picked up by the dependency packager.

I'm looking at where those are and I'll add a new release once they get built.

Thanks for pointing it out

**Comment by ericmehl** [comment]
Hey @xtvjxk123456, give the latest release a try: https://github.com/hypothetical-inc/gaffer/releases/tag/0.57.3.1

It's working fine loading the USD kitchen scene now - let me know how it works for you.

**Comment by xtvjxk123456** [comment]
usd related thing is ok.
got another issue
![Snipaste_2020-06-04_10-20-46](https://user-images.githubusercontent.com/8720281/83711516-fe791300-a655-11ea-9da8-817ade053b6a.jpg)

**Comment by xtvjxk123456** [comment]
and more unstable

**Comment by ericmehl** [comment]
Alrighty, give this one a try: https://github.com/hypothetical-inc/gaffer/releases/tag/0.57.3.2

I had been building these lately on a second machine that I hadn't updated to the newer Arnold.

**Comment by xtvjxk123456** [comment]
it is working now,almost  perfect!
thank you for your effort.
