### ISSUE TITLE
how to use 3delight nsi in gaffer

### ISSUE THREAD

**Issue by xtvjxk123456** [hypothetical-inc/gaffer#9]
3delight nsi has been installed,
 DELIGHT is also present in the environment variable,
 when the gaffer is opened， there is no 3delight node

**Comment by ericmehl** [comment]
Unfortunately I don't use 3delight so I can't offer much help here. I believe, but am not sure, that the main Gaffer builds are somewhat out of date with modern 3delight as well.

If you want to try and debug it yourself, I'd recommend looking through the `gaffer` file which is used to launch Gaffer on Linux. That should have some hints at what paths need to be setup to point Gaffer to the right places for 3delight. Setting those in the `gaffer.bat` file may get 3delight working on Windows.
